spring:
  application:
    name: eureka-server

server:
  port: 8070

eureka:
  instance:
    hostname: eurekaserver
    #hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5

#Enable all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
    health:
      enabled: true
      show-details: always