server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka
      #defaultZone: http://localhost:8070/eureka

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      #Automated mapping of routes via service discovery
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      #Manually mapping routes using service discovery
      routes:
        - id: organization-service
          uri: lb://organization-service

          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: licensing-service
          uri: lb://licensing-service

          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1

management:
  endpoints:
    web:
      exposures:
        include: "*"
    enabled-by-default: true
    health:
      enabled: true
      show-details: always